# Generated by Django 4.1.6 on 2023-02-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ArxivPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arxiv_id', models.CharField(max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('longer_summary', models.TextField(blank=True, null=True)),
                ('link_doi', models.URLField(blank=True, null=True)),
                ('link_homepage', models.URLField(blank=True, null=True)),
                ('published_arxiv', models.DateField(blank=True, null=True)),
                ('journal_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_arxiv', models.DateField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, to='summarizer.author')),
            ],
        ),
    ]
