# Generated by Django 4.1.6 on 2023-02-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PapereAuthor',
            new_name='PaperAuthor',
        ),
    ]
