# Generated by Django 4.1.6 on 2023-02-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='affiliation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
