# Generated by Django 4.1.6 on 2023-02-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0002_alter_author_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='arxivpaper',
            name='blog',
            field=models.TextField(blank=True, null=True),
        ),
    ]
