# Generated by Django 4.1.6 on 2023-02-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0003_customuser_address_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
