# Generated by Django 4.1.6 on 2023-02-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0003_arxivpaper_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='arxivpaper',
            name='license',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
