# Generated by Django 4.1.6 on 2023-02-21 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0004_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arxivpaper',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='arxivpaper',
            name='longer_summary',
        ),
        migrations.RemoveField(
            model_name='arxivpaper',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='arxivpaper',
            name='summary',
        ),
        migrations.CreateModel(
            name='SummaryPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('longer_summary', models.TextField(blank=True, null=True)),
                ('blog', models.TextField(blank=True, null=True)),
                ('lang', models.CharField(default='en', max_length=10)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarizer.arxivpaper')),
            ],
        ),
    ]
