# Generated by Django 4.1.6 on 2023-02-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0005_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='arxivpaper',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
