# Generated by Django 4.1.6 on 2023-02-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0006_remove_arxivpaper_total_votes_vote_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickledData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arxiv_id', models.CharField(max_length=20)),
                ('docstore_pickle', models.BinaryField()),
                ('buffer', models.BinaryField()),
                ('index_to_docstore_id_pickle', models.BinaryField()),
            ],
        ),
    ]
