# Generated by Django 4.1.6 on 2023-02-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0007_pickleddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickleddata',
            name='docstore_pickle',
            field=models.BinaryField(editable=True),
        ),
    ]
