# Generated by Django 4.1.6 on 2023-02-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0007_customuser_alter_arxivpaper_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
