# Generated by Django 4.1.6 on 2023-02-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0009_paperhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='ip_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
