# Generated by Django 4.1.6 on 2023-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0012_aiassistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistant',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aiassistant',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
