# Generated by Django 4.1.6 on 2023-02-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0014_alter_aiassistant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarypaper',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
