# Generated by Django 4.1.6 on 2023-03-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0016_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperhistory',
            name='ip_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperhistory',
            name='lang',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
