# Generated by Django 4.1.6 on 2023-03-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0018_alter_paperhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperhistory',
            name='updated',
        ),
    ]
