# Generated by Django 4.1.6 on 2023-03-28 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summarizer', '0021_vote_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arxiv_id', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('lang', models.CharField(default='en', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
