# Generated by Django 4.1.6 on 2023-03-30 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0022_pdfhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('from_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_paper', to='summarizer.arxivpaper')),
                ('to_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_paper', to='summarizer.arxivpaper')),
            ],
        ),
        migrations.AddField(
            model_name='arxivpaper',
            name='closest_papers',
            field=models.ManyToManyField(related_name='closest_to', through='summarizer.PaperScore', to='summarizer.arxivpaper'),
        ),
    ]
