# Generated by Django 4.1.6 on 2023-04-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0023_paperscore_arxivpaper_closest_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistant',
            name='ip_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
